# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mark_attendance_pb2 as mark__attendance__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mark_attendance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AttendanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MarkAttendance = channel.unary_unary(
                '/attendance.AttendanceService/MarkAttendance',
                request_serializer=mark__attendance__pb2.AttendanceRequest.SerializeToString,
                response_deserializer=mark__attendance__pb2.AttendanceResponse.FromString,
                _registered_method=True)


class AttendanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MarkAttendance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttendanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MarkAttendance': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAttendance,
                    request_deserializer=mark__attendance__pb2.AttendanceRequest.FromString,
                    response_serializer=mark__attendance__pb2.AttendanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'attendance.AttendanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('attendance.AttendanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttendanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MarkAttendance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attendance.AttendanceService/MarkAttendance',
            mark__attendance__pb2.AttendanceRequest.SerializeToString,
            mark__attendance__pb2.AttendanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
