# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mark_attendance.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15mark_attendance.proto\x12\nattendance\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n\x11\x41ttendanceRequest\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tembedding\x18\x02 \x03(\x02\"e\n\x12\x41ttendanceResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x12\n\nstudent_id\x18\x02 \x01(\x03\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2f\n\x11\x41ttendanceService\x12Q\n\x0eMarkAttendance\x12\x1d.attendance.AttendanceRequest\x1a\x1e.attendance.AttendanceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mark_attendance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTENDANCEREQUEST']._serialized_start=70
  _globals['_ATTENDANCEREQUEST']._serialized_end=150
  _globals['_ATTENDANCERESPONSE']._serialized_start=152
  _globals['_ATTENDANCERESPONSE']._serialized_end=253
  _globals['_ATTENDANCESERVICE']._serialized_start=255
  _globals['_ATTENDANCESERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
