from .Student import Student
from .Face import Face
from .Attendance import Attendance
from .AcademicCalendar import AcademicCalendar
from .Timetable import Timetable
from .StudentSemesterSemno import StudentSemesterSemno
from .TimetableCourseSemesterSemno import TimetableCourseSemesterSemno
from .CourseCalendarSemesterSemno import CourseCalendarSemesterSemno
from .User import User
from .Course import Course
from .Semester import Semester
from .Subject import Subject
from .ClassEntry import ClassEntry
