from .Student import Student
from .Face import Face
from .Attendance import Attendance
from .StudentSemesterSemno import StudentSemesterSemno
from .TimetableCourseSemesterSemno import TimetableCourseSemesterSemno
from .CourseCalendarSemesterSemno import CourseCalendarSemesterSemno
from .AcademicCalendar import AcademicCalendar
from .User import User
from .Timetable import Timetable
from .Course import Course
from .Semester import Semester
from .Subject import Subject
from .ClassEntry import ClassEntry
